spring:
  application:
    name: demotestmaven
  datasource:
    # url: jdbc:mysql://localhost:3307/demotestmaven?useSSL=false&allowPublicKeyRetrieval=true
    # username: demouser
    # password: demopassword
    url: jdbc:mysql://db-test.cjkocssqm352.eu-central-1.rds.amazonaws.com:3306/testdb
    username: root
    password: Linhhiep273
    driver-class-name: com.mysql.cj.jdbc.Driver
  docker:
    compose:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: false
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    time-zone: UTC

server:
  port: 8082
logging:
  level:
    org:
      hibernate:
        SQL: OFF
        type:
          descriptor:
            sql:
              BasicBinder: OFF
    com:
      yourpackage: DEBUG
  